### PR TITLE
Update composer

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

## Changelog

```markdown
### Added
- Added support for `psr/log` 2 and 3
### Removed
- Removed support for PHP < 7.3
```

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]
Just by curiosity, what's the need ? (this library is deprecated)

**Comment by jordisala1991** [comment]
> Just by curiosity, what's the need ? (this library is deprecated)

Without this change we are stuck on SonataAdminBundle psr/log 1.0

**Comment by jordisala1991** [comment]
This library is used on BlockBundle I think. Even if it is suposed to be "deprecated" it is not unused.

**Comment by VincentLanglet** [comment]
> Even if it is suposed to be "deprecated" it is not unused.

Sure I was wondering where it was used.

> This library is used on BlockBundle I think.

Indeed :'(
We have to tackle https://github.com/sonata-project/SonataBlockBundle/issues/663

**Pull request merged**
