### PR TITLE
DevKit updates for 2.x branch

### PR DESCRIPTION
**Pull request by SonataCI**

### CODE REVIEW

**Comment by OskarStark** [comment]
Can you check the tests @VincentLanglet ?

**Comment by VincentLanglet** [comment]
> Can you check the tests @VincentLanglet ?

Lot of tests are skipped because the apcu extension is missing, we should add it to this repository and the cachebundle one

**Comment by OskarStark** [comment]
> Lot of tests are skipped because the apcu extension is missing, we should add it to this repository and the cachebundle one

Open for a PR? 😄

**Comment by VincentLanglet** [comment]
> > Lot of tests are skipped because the apcu extension is missing, we should add it to this repository and the cachebundle one
> 
> Open for a PR? 😄

WIP: https://github.com/sonata-project/dev-kit/pull/1346/files

**Comment by VincentLanglet** [comment]
Test are working locally now. But I don't know why I have this weird error with $blacklist on CI that I didn't get before....

**Comment by OskarStark** [comment]
You mean this one?
```
1) Sonata\Cache\Tests\Cache\Invalidation\DoctrinePHPCRODMListenerTest::test
Cannot stub or mock class or interface "Doctrine\Persistence\Event\LifecycleEventArgs" which does not exist
```

**Comment by VincentLanglet** [comment]
This is working now @OskarStark

**Review by VincentLanglet — APPROVED** [review]

**Review by VincentLanglet — APPROVED** [review]

**Pull request merged**
