### PR TITLE
Allow predis 1

### PR DESCRIPTION
**Pull request by greg0ire**
I am targetting this branch, because this is BC.

The change is in the `require-dev` section, so pedantic.

### CODE REVIEW

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Comment by greg0ire** [comment]
ping @core23

**Comment by core23** [comment]
I don't use `predis`, so I can't review it :/

**Comment by greg0ire** [comment]
@core23 do you think I'm using predis ?

**Comment by core23** [comment]
How can you check if this will work? Allowing a new major won't work in all cases.

**Comment by greg0ire** [comment]
The test suite is fine with it, and that's all that should matter. People that find something broken can either use the older `0.*` version, or provide a patch.

**Comment by greg0ire** [comment]
Plus, it's a require-dev dependency.

**Comment by greg0ire** [comment]
ping @core23

**Pull request merged**
